[ESKL-130/show-opponent-status] - Shows a toast when opponent finishes
Aptoide/2048 pull request #30
Opened 2021-11-18 11:00 UTC by nnelas

**What does this PR do?**

- Shows a toast when opponent finishes the match

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] 2048/2048/src/main/java/com/appcoins/eskills2048/MainActivity.java

**How should this be manually tested?**

Enter a new game with 2 devices. End game in one of them. On the other one you should see a Toast appearing saying your opponent has finished the game.

**What are the relevant tickets?**

  Tickets related to this pull-request: [ESKL-130](https://aptoide.atlassian.net/browse/ESKL-130)

**Questions:**

N/A

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] If yes - Database migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

2021-11-18 13:13 UTC, Trinkes requested changes

2021-11-18 13:13 UTC, Trinkes commented on 2048/2048/src/main/java/com/appcoins/eskills2048/MainActivity.java
> +            getRoomUseCase, setGameStatusLocallyUseCase, new NotifyOpponentFinishedUseCase(this)),
```suggestion
            getRoomUseCase, setGameStatusLocallyUseCase, new NotifyOpponentFinishedUseCase(opponent -> view.game.onOpponentFinished(opponent))),
```

2021-11-18 13:13 UTC, Trinkes commented on 2048/2048/src/main/java/com/appcoins/eskills2048/vm/MainGameViewModel.java
> +  public void notify(User opponent) {
```suggestion

```

2021-11-18 13:13 UTC, Trinkes commented on 2048/2048/src/main/java/com/appcoins/eskills2048/vm/MainGameViewModel.java
> +    notifyOpponentFinishedUseCase.notify(opponent);
```suggestion

```

2021-11-18 13:13 UTC, Trinkes commented on 2048/2048/src/main/java/com/appcoins/eskills2048/vm/MainGameViewModel.java
> +  }
```suggestion

```

2021-11-22 09:42 UTC, nnelas commented on 2048/2048/src/main/java/com/appcoins/eskills2048/usecase/NotifyOpponentFinishedUseCase.java
> +@Singleton public class NotifyOpponentFinishedUseCase {
didn't knew about that, changing

2021-11-23 15:02 UTC, merged